# Generated by Django 5.1.3 on 2024-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
